### PR TITLE
Tflite inference

### PR DESCRIPTION
**Pull request by MrRiahi**
Thanks for your help. I create a new branch named tflite_inference and create a new PR.

### CODE REVIEW

**Comment by de-code** [comment]
Hi @MrRiahi I just tried to update the branch with the latest dependencies but I am getting permission denied.

Would you be okay to enable `Allow edits from maintainers`? (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
Otherwise I won't be able to update the PR.

**Comment by MrRiahi** [comment]
Hi @de-code 
Thanks for your help. I enable `Allow edits by maintainers`.

**Comment by de-code** [comment]
> Hi @de-code Thanks for your help. I enable `Allow edits by maintainers`.

Okay, not sure why I am still getting permission errors. Maybe I am using it incorrectly.
In the meantime I was working on #167 based on your code.
It is mostly working. I had to make a few more changes in order to support the API as is.

**Comment by de-code** [comment]
closing in favour of #167

**Pull request closed without merging**
